Added models for customers, departments, employees, orders, and produ…
Unaccountable-Magpie/BangazonAPI2 pull request #3
Opened 2018-09-13 15:12 UTC by austingorman

…ct orders

Purpose:
Created models

How it fits in context of the project:
We are creating a few models per person

Specific Feature affected:
Employees, Departments, Customers, Orders, and ProductOrders

How to test (Be thorough!):

Look at it with your eyes. The models should be there.

2018-09-13 15:18 UTC, Rian501 commented
Please elaborate on steps to test. It's not only that the model should exist, but what should we be looking for in it?

2018-09-13 16:20 UTC, Aux5 commented
Looks good!

2018-09-13 16:45 UTC, Rian501 commented on Models/Customers.cs
> +        List<Customers> CustomerList = new List<Customers>();
A customer won't actually have a list of customers inside it.
A customer DOES need two lists-- check the customers ticket -- you will need lists for the things that can be included
https://github.com/nashville-software-school/csharp-bangazonapi-boilerplate/issues/1

2018-09-13 16:46 UTC, Rian501 commented on Models/Departments.cs
> +        List<Departments> DepartmentList = new List<Departments>();
Like Customers, this won't have a list of itself within it. Please review.

2018-09-13 16:47 UTC, Rian501 requested changes
Check the tickets for each of these to see what foreign properties need to be included in the model. Also, none of them need a list of themselves.

2018-09-13 18:51 UTC, austingorman commented
I think I have the lists fixed

2018-09-13 19:13 UTC, Rian501 commented on Models/Employees.cs
> +        public Departments DepartmentsId { get; set; }
Once we get the Department ID we can then get the Dept itself -- like the Customer Customer on the Order.cs class

2018-09-13 19:14 UTC, Rian501 reviewed
One small change that I could find.

2018-09-13 19:50 UTC, AmandaM04 commented
looks good! You have fixed the small issues that I found

2018-09-14 13:43 UTC, Rian501 approved these changes
Looks good to me!

2018-09-14 14:14 UTC, merged